### ISSUE TITLE
li + h3

### ISSUE THREAD

**Issue by DanBaDo** [alfonsoporto22/Curriculum#1]
https://github.com/alfonsoporto22/Curriculum/blob/64dffe71c19630a1cc42bd1c62549ea85dd16cd8/src/index.html#L54-L70

Podríamos usar `<li>` junto conn `<h3>` para reforzar el significado de la lista frente a los buscadores.

```html
<li><h3>Técnico de Calidad - Faurecia</h3></li>
```

Puede que esta propuesta sea superflua... no me hagas mucho caso.

**Comment by alfonsoporto22** [comment]
Hecho! Gracias!
